select * from tblteamentry;


update tblteamentry set points = 52 where seq= 1;
update tblteamentry set points = 50 where seq= 2;
update tblteamentry set points = 37 where seq= 3;
update tblteamentry set points = 40 where seq= 4;
update tblteamentry set points = 28 where seq= 5;
update tblteamentry set points = 52 where seq= 6;
update tblteamentry set points = 60 where seq= 7;
update tblteamentry set points = 35 where seq= 8;
update tblteamentry set points = 34 where seq= 9;
update tblteamentry set points = 40 where seq= 10;
update tblteamentry set points = 46 where seq= 11;
update tblteamentry set points = 36 where seq= 12;
update tblteamentry set points = 49 where seq= 13;
update tblteamentry set points = 40 where seq= 14;
update tblteamentry set points = 34 where seq= 15;
update tblteamentry set points = 35 where seq= 16;
update tblteamentry set points = 47 where seq= 17;
update tblteamentry set points = 30 where seq= 18;
update tblteamentry set points = 43 where seq= 19;
update tblteamentry set points = 47 where seq= 20;
update tblteamentry set points = 35 where seq= 21;
update tblteamentry set points = 39 where seq= 22;
update tblteamentry set points = 37 where seq= 23;
update tblteamentry set points = 46 where seq= 24;
update tblteamentry set points = 46 where seq= 25;
update tblteamentry set points = 35 where seq= 26;
update tblteamentry set points = 38 where seq= 27;
update tblteamentry set points = 45 where seq= 28;
update tblteamentry set points = 52 where seq= 29;
update tblteamentry set points = 51 where seq= 30;
update tblteamentry set points = 33 where seq= 31;
update tblteamentry set points = 45 where seq= 32;
update tblteamentry set points = 26 where seq= 33;
update tblteamentry set points = 50 where seq= 34;
update tblteamentry set points = 44 where seq= 35;
update tblteamentry set points = 29 where seq= 36;
update tblteamentry set points = 36 where seq= 37;
update tblteamentry set points = 42 where seq= 38;
update tblteamentry set points = 50 where seq= 39;
update tblteamentry set points = 39 where seq= 40;
update tblteamentry set points = 42 where seq= 41;
update tblteamentry set points = 51 where seq= 42;
update tblteamentry set points = 52 where seq= 43;
update tblteamentry set points = 34 where seq= 44;
update tblteamentry set points = 48 where seq= 45;
update tblteamentry set points = 40 where seq= 46;
update tblteamentry set points = 55 where seq= 47;
update tblteamentry set points = 30 where seq= 48;

commit;
select * from tblteamentry;
